name: Build
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: caches-${{ hashFiles('build.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            caches-

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/*.jar
